//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Disk.Properties.Config {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    public sealed partial class Config : global::System.Configuration.ApplicationSettingsBase {
        
        private static Config defaultInstance = ((Config)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Config())));
        
        public static Config Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public float X_MAX_ANGLE {
            get {
                return ((float)(this["X_MAX_ANGLE"]));
            }
            set {
                this["X_MAX_ANGLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public float Y_MAX_ANGLE {
            get {
                return ((float)(this["Y_MAX_ANGLE"]));
            }
            set {
                this["Y_MAX_ANGLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string IP {
            get {
                return ((string)(this["IP"]));
            }
            set {
                this["IP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9998")]
        public int PORT {
            get {
                return ((int)(this["PORT"]));
            }
            set {
                this["PORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int TARGET_MIN_TIME {
            get {
                return ((int)(this["TARGET_MIN_TIME"]));
            }
            set {
                this["TARGET_MIN_TIME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int TARGET_MAX_TIME {
            get {
                return ((int)(this["TARGET_MAX_TIME"]));
            }
            set {
                this["TARGET_MAX_TIME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int MOVE_TIME {
            get {
                return ((int)(this["MOVE_TIME"]));
            }
            set {
                this["MOVE_TIME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int SHOT_TIME {
            get {
                return ((int)(this["SHOT_TIME"]));
            }
            set {
                this["SHOT_TIME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int USER_INI_SPEED {
            get {
                return ((int)(this["USER_INI_SPEED"]));
            }
            set {
                this["USER_INI_SPEED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int USER_INI_RADIUS {
            get {
                return ((int)(this["USER_INI_RADIUS"]));
            }
            set {
                this["USER_INI_RADIUS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int ENEMY_INI_SPEED {
            get {
                return ((int)(this["ENEMY_INI_SPEED"]));
            }
            set {
                this["ENEMY_INI_SPEED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int ENEMY_INI_RADIUS {
            get {
                return ((int)(this["ENEMY_INI_RADIUS"]));
            }
            set {
                this["ENEMY_INI_RADIUS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int TARGET_INI_RADIUS {
            get {
                return ((int)(this["TARGET_INI_RADIUS"]));
            }
            set {
                this["TARGET_INI_RADIUS"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public int SCREEN_INI_WIDTH {
            get {
                return ((int)(this["SCREEN_INI_WIDTH"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public int SCREEN_INI_HEIGHT {
            get {
                return ((int)(this["SCREEN_INI_HEIGHT"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ENEMIES_NUM {
            get {
                return ((int)(this["ENEMIES_NUM"]));
            }
            set {
                this["ENEMIES_NUM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("userWND.log")]
        public string USER_WND_LOG_FILE {
            get {
                return ((string)(this["USER_WND_LOG_FILE"]));
            }
            set {
                this["USER_WND_LOG_FILE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("userCEN.log")]
        public string USER_CEN_LOG_FILE {
            get {
                return ((string)(this["USER_CEN_LOG_FILE"]));
            }
            set {
                this["USER_CEN_LOG_FILE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("userANG.log")]
        public string USER_ANG_LOG_FILE {
            get {
                return ((string)(this["USER_ANG_LOG_FILE"]));
            }
            set {
                this["USER_ANG_LOG_FILE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("enemyWND")]
        public string ENEMY_WND_LOG_NAME {
            get {
                return ((string)(this["ENEMY_WND_LOG_NAME"]));
            }
            set {
                this["ENEMY_WND_LOG_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("enemyCEN")]
        public string ENEMY_CEN_LOG_NAME {
            get {
                return ((string)(this["ENEMY_CEN_LOG_NAME"]));
            }
            set {
                this["ENEMY_CEN_LOG_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("enemyANG")]
        public string ENEMY_ANG_LOG_NAME {
            get {
                return ((string)(this["ENEMY_ANG_LOG_NAME"]));
            }
            set {
                this["ENEMY_ANG_LOG_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(";")]
        public char LOG_SEPARATOR {
            get {
                return ((char)(this["LOG_SEPARATOR"]));
            }
            set {
                this["LOG_SEPARATOR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".log")]
        public string LOG_EXTENSION {
            get {
                return ((string)(this["LOG_EXTENSION"]));
            }
            set {
                this["LOG_EXTENSION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ENEMY_LOG_PATH {
            get {
                return ((string)(this["ENEMY_LOG_PATH"]));
            }
            set {
                this["ENEMY_LOG_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public global::System.Drawing.Color USER_COLOR {
            get {
                return ((global::System.Drawing.Color)(this["USER_COLOR"]));
            }
            set {
                this["USER_COLOR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float ANGLE_X_SHIFT {
            get {
                return ((float)(this["ANGLE_X_SHIFT"]));
            }
            set {
                this["ANGLE_X_SHIFT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float ANGLE_Y_SHIFT {
            get {
                return ((float)(this["ANGLE_Y_SHIFT"]));
            }
            set {
                this["ANGLE_Y_SHIFT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int CALIBRATION_TIMEOUT {
            get {
                return ((int)(this["CALIBRATION_TIMEOUT"]));
            }
            set {
                this["CALIBRATION_TIMEOUT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public int RECEIVE_TIMEOUT {
            get {
                return ((int)(this["RECEIVE_TIMEOUT"]));
            }
            set {
                this["RECEIVE_TIMEOUT"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Диск. Данные")]
        public string MAIN_DIR_PATH {
            get {
                return ((string)(this["MAIN_DIR_PATH"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("maps")]
        public string MAPS_DIR_PATH {
            get {
                return ((string)(this["MAPS_DIR_PATH"]));
            }
            set {
                this["MAPS_DIR_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int MAP_ID {
            get {
                return ((int)(this["MAP_ID"]));
            }
            set {
                this["MAP_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ru-RU")]
        public string LANGUAGE {
            get {
                return ((string)(this["LANGUAGE"]));
            }
            set {
                this["LANGUAGE"] = value;
            }
        }
    }
}
