//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Disk.Properties.Langs.ExcelFiller {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExcelFillerLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExcelFillerLocalization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Disk.Properties.Langs.ExcelFiller.ExcelFillerLocalization", typeof(ExcelFillerLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accuracy.
        /// </summary>
        internal static string Accuracy {
            get {
                return ResourceManager.GetString("Accuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approach speed.
        /// </summary>
        internal static string ApproachSpeed {
            get {
                return ResourceManager.GetString("ApproachSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average speed.
        /// </summary>
        internal static string AverageSpeed {
            get {
                return ResourceManager.GetString("AverageSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сonvex hull area.
        /// </summary>
        internal static string ConvexHullArea {
            get {
                return ResourceManager.GetString("ConvexHullArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursor radius.
        /// </summary>
        internal static string CursorRadius {
            get {
                return ResourceManager.GetString("CursorRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date/Time.
        /// </summary>
        internal static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deviation.
        /// </summary>
        internal static string Deviation {
            get {
                return ResourceManager.GetString("Deviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        internal static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ellipse area.
        /// </summary>
        internal static string EllipseArea {
            get {
                return ResourceManager.GetString("EllipseArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Excel.
        /// </summary>
        internal static string ExportToExcel {
            get {
                return ResourceManager.GetString("ExportToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front left foot.
        /// </summary>
        internal static string FrontLeftFoot {
            get {
                return ResourceManager.GetString("FrontLeftFoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front right foot.
        /// </summary>
        internal static string FrontRightFoot {
            get {
                return ResourceManager.GetString("FrontRightFoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full path.
        /// </summary>
        internal static string FullPath {
            get {
                return ResourceManager.GetString("FullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        internal static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mathematical expectation.
        /// </summary>
        internal static string MathExp {
            get {
                return ResourceManager.GetString("MathExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum tilt angle of the complex.
        /// </summary>
        internal static string MaxAngle {
            get {
                return ResourceManager.GetString("MaxAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path in target.
        /// </summary>
        internal static string PathInTarget {
            get {
                return ResourceManager.GetString("PathInTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to target.
        /// </summary>
        internal static string PathToTarget {
            get {
                return ResourceManager.GetString("PathToTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile prejection.
        /// </summary>
        internal static string ProfileProjection {
            get {
                return ResourceManager.GetString("ProfileProjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target center.
        /// </summary>
        internal static string TargetCenter {
            get {
                return ResourceManager.GetString("TargetCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target number.
        /// </summary>
        internal static string TargetNum {
            get {
                return ResourceManager.GetString("TargetNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target radius.
        /// </summary>
        internal static string TargetRadius {
            get {
                return ResourceManager.GetString("TargetRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
    }
}
