//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Disk.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Disk.Properties.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance (in angles).
        /// </summary>
        public static string Paint_AngleDistance {
            get {
                return ResourceManager.GetString("Paint.AngleDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed (in angles).
        /// </summary>
        public static string Paint_AngleSpeed {
            get {
                return ResourceManager.GetString("Paint.AngleSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approach speed.
        /// </summary>
        public static string Paint_ApproachSpeed {
            get {
                return ResourceManager.GetString("Paint.ApproachSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection lost.
        /// </summary>
        public static string Paint_ConnectionLost {
            get {
                return ResourceManager.GetString("Paint.ConnectionLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispersion.
        /// </summary>
        public static string Paint_Dispersion {
            get {
                return ResourceManager.GetString("Paint.Dispersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map is empty.
        /// </summary>
        public static string Paint_EmptyMap {
            get {
                return ResourceManager.GetString("Paint.EmptyMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average shift from center.
        /// </summary>
        public static string Paint_MathExp {
            get {
                return ResourceManager.GetString("Paint.MathExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wasted.
        /// </summary>
        public static string Paint_Over {
            get {
                return ResourceManager.GetString("Paint.Over", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string Paint_Path {
            get {
                return ResourceManager.GetString("Paint.Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to target.
        /// </summary>
        public static string Paint_PathToTarget {
            get {
                return ResourceManager.GetString("Paint.PathToTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string Paint_Score {
            get {
                return ResourceManager.GetString("Paint.Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deviation.
        /// </summary>
        public static string Paint_StandartDeviation {
            get {
                return ResourceManager.GetString("Paint.StandartDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Paint_Stop {
            get {
                return ResourceManager.GetString("Paint.Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Paint_Time {
            get {
                return ResourceManager.GetString("Paint.Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk. Paint field.
        /// </summary>
        public static string Paint_Title {
            get {
                return ResourceManager.GetString("Paint.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind rose.
        /// </summary>
        public static string Paint_WindRose {
            get {
                return ResourceManager.GetString("Paint.WindRose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind rose for target.
        /// </summary>
        public static string Paint_WindRoseForTarget {
            get {
                return ResourceManager.GetString("Paint.WindRoseForTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        public static string UserData_Birthday {
            get {
                return ResourceManager.GetString("UserData.Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the fields is empty.
        /// </summary>
        public static string UserData_FieldIsEmpty {
            get {
                return ResourceManager.GetString("UserData.FieldIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string UserData_Map {
            get {
                return ResourceManager.GetString("UserData.Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string UserData_Name {
            get {
                return ResourceManager.GetString("UserData.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string UserData_Start {
            get {
                return ResourceManager.GetString("UserData.Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string UserData_Surname {
            get {
                return ResourceManager.GetString("UserData.Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User data.
        /// </summary>
        public static string UserData_Title {
            get {
                return ResourceManager.GetString("UserData.Title", resourceCulture);
            }
        }
    }
}
