//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Disk.Properties.Langs.Session {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SessionLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SessionLocalization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Disk.Properties.Langs.Session.SessionLocalization", typeof(SessionLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accuracy.
        /// </summary>
        public static string Accuracy {
            get {
                return ResourceManager.GetString("Accuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max angles (X, Y}.
        /// </summary>
        public static string Angles {
            get {
                return ResourceManager.GetString("Angles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approach speed.
        /// </summary>
        public static string ApproachSpeed {
            get {
                return ResourceManager.GetString("ApproachSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average speed.
        /// </summary>
        public static string AverageSpeed {
            get {
                return ResourceManager.GetString("AverageSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convex hull area.
        /// </summary>
        public static string ConvexHullArea {
            get {
                return ResourceManager.GetString("ConvexHullArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursor image path.
        /// </summary>
        public static string CursorImagePath {
            get {
                return ResourceManager.GetString("CursorImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursor radius.
        /// </summary>
        public static string CursorRadius {
            get {
                return ResourceManager.GetString("CursorRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date/Time.
        /// </summary>
        public static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deviation.
        /// </summary>
        public static string Deviation {
            get {
                return ResourceManager.GetString("Deviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        public static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ellipse area.
        /// </summary>
        public static string EllipseArea {
            get {
                return ResourceManager.GetString("EllipseArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorCaption {
            get {
                return ResourceManager.GetString("ErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to excel.
        /// </summary>
        public static string ExportToExcel {
            get {
                return ResourceManager.GetString("ExportToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP.
        /// </summary>
        public static string Ip {
            get {
                return ResourceManager.GetString("Ip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Math expectation.
        /// </summary>
        public static string MathExp {
            get {
                return ResourceManager.GetString("MathExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frames per second.
        /// </summary>
        public static string MoveTime {
            get {
                return ResourceManager.GetString("MoveTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dataset contains errors or empty.
        /// </summary>
        public static string NoContentError {
            get {
                return ResourceManager.GetString("NoContentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path in target.
        /// </summary>
        public static string PathInTarget {
            get {
                return ResourceManager.GetString("PathInTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to target.
        /// </summary>
        public static string PathToTarget {
            get {
                return ResourceManager.GetString("PathToTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save failed.
        /// </summary>
        public static string SaveFailed {
            get {
                return ResourceManager.GetString("SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample rate, Hz.
        /// </summary>
        public static string ShotTime {
            get {
                return ResourceManager.GetString("ShotTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target time to live, ms.
        /// </summary>
        public static string TargetHp {
            get {
                return ResourceManager.GetString("TargetHp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target image path.
        /// </summary>
        public static string TargetImagePath {
            get {
                return ResourceManager.GetString("TargetImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target number.
        /// </summary>
        public static string TargetNum {
            get {
                return ResourceManager.GetString("TargetNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target radius.
        /// </summary>
        public static string TargetRadius {
            get {
                return ResourceManager.GetString("TargetRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
    }
}
