//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Disk.Properties.Langs.AttemptResult {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AttemptResultLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AttemptResultLocalization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Disk.Properties.Langs.AttemptResult.AttemptResultLocalization", typeof(AttemptResultLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current 
        ///   's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accuracy.
        /// </summary>
        public static string Accuracy {
            get {
                return ResourceManager.GetString("Accuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approach speed.
        /// </summary>
        public static string ApproachSpeed {
            get {
                return ResourceManager.GetString("ApproachSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average speed.
        /// </summary>
        public static string AverageSpeed {
            get {
                return ResourceManager.GetString("AverageSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convex hull area.
        /// </summary>
        public static string ConvexHullArea {
            get {
                return ResourceManager.GetString("ConvexHullArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequencies diagram.
        /// </summary>
        public static string Diagram {
            get {
                return ResourceManager.GetString("Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ellipse area.
        /// </summary>
        public static string EllipseArea {
            get {
                return ResourceManager.GetString("EllipseArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full path area.
        /// </summary>
        public static string FullPathArea {
            get {
                return ResourceManager.GetString("FullPathArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide cursor.
        /// </summary>
        public static string HideCursor {
            get {
                return ResourceManager.GetString("HideCursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide target.
        /// </summary>
        public static string HideTarget {
            get {
                return ResourceManager.GetString("HideTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.
        /// </summary>
        public static string LeftFoot {
            get {
                return ResourceManager.GetString("LeftFoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average shift from center.
        /// </summary>
        public static string MathExp {
            get {
                return ResourceManager.GetString("MathExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No content for diagram.
        /// </summary>
        public static string NoContentForDiagramError {
            get {
                return ResourceManager.GetString("NoContentForDiagramError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No content for path.
        /// </summary>
        public static string NoContentForPathError {
            get {
                return ResourceManager.GetString("NoContentForPathError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path in target.
        /// </summary>
        public static string PathInTarget {
            get {
                return ResourceManager.GetString("PathInTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path in target area.
        /// </summary>
        public static string PathInTargetArea {
            get {
                return ResourceManager.GetString("PathInTargetArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PathToTarget.
        /// </summary>
        public static string PathToTarget {
            get {
                return ResourceManager.GetString("PathToTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to target area.
        /// </summary>
        public static string PathToTargetArea {
            get {
                return ResourceManager.GetString("PathToTargetArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply.
        /// </summary>
        public static string Reply {
            get {
                return ResourceManager.GetString("Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.
        /// </summary>
        public static string RightFoot {
            get {
                return ResourceManager.GetString("RightFoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deviation.
        /// </summary>
        public static string StandartDeviation {
            get {
                return ResourceManager.GetString("StandartDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
    }
}
